### ISSUE TITLE
Добавить узлы для подсчёта клиентов

### ISSUE THREAD

**Issue by Sranych** [Relicta-Team/ReNodes#80]
Есть мысль реализовать ограничение на выбор роли, если на сервере до начала раунда мало игроков. Например, если всего есть 15 ролей, а на сервере всего 10 человек, 5 необязательных ролей нельзя будет выбрать.

Для этого нужны дополнительные узлы:
- Количество игроков на сервере
- Количество игроков в лобби
- Состояние игры

Возможно нужно добавить что-то еще, но сейчас я не могу сформулировать более чётко.

**Comment by Yobas** [comment]
"Все клиенты"
"Клиентов на сервере"
"Клиентов в игре"
"Клиентов в лобби"
"Макс. клиентов"
"Состояние игры"
"Статус 'Выбора режима'"
"Статус 'Подготовка'"
"Статус 'Игра'"
"Статус 'Конец раунда'"
"Клиенты с уровнем доступа"
"Найти клиента по никнейму"
"Найти клиента по SteamID"

**Comment by Yobas** [comment]
@Sranych если больше ничего не надо по этой задаче, то будет добавлено после полуночи

**Comment by Yobas** [comment]
реализовано
