### ISSUE TITLE
Добавить узлы для возможности задать воспоминания и краткое описание роли

### ISSUE THREAD

**Issue by Sranych** [Relicta-Team/ReNodes#85]
Нужны узлы для возможности задать воспоминания и краткое описание роли при инспектирование через F1

Так же нужно что бы к этим нодам можно было подключить массив что бы была возможно перебирать разные варианты описаний

**Comment by Yobas** [comment]
Узлы управления воспоминаниями добавлены. Само воспоминание является обычной строкой и через условную логику (ветки) ты можешь настроить итоговое воспоминание, которое будет добавлено персонажу
